# Generated by Django 4.2.20 on 2025-03-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicine', to='api.user'),
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Hour', models.TimeField()),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='api.medicine')),
            ],
        ),
    ]
