# Generated by Django 4.2.20 on 2025-03-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_medicine_user_medicineschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PhoneNumber',
        ),
    ]
