# Generated by Django 4.2.20 on 2025-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_email_remove_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CI',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
