# Generated by Django 4.2.20 on 2025-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='CI',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
