# Generated by Django 4.2.20 on 2025-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_id_alter_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineschedule',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All Days', 'All Days')], max_length=20),
        ),
    ]
