# Generated by Django 4.2.20 on 2025-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_medicineschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
