# Generated by Django 4.2.20 on 2025-04-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_age_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicine', to='api.user'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='Medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='api.medicine'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CI',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
