# Generated by Django 4.2.20 on 2025-05-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_phonenumber_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineschedule',
            name='Medicine',
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='Dose',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='MedicineName',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
